Round cart condition values
tastyigniter/flame pull request #34
Opened 2021-05-27 06:16 UTC by ryanmitchell

2021-05-31 08:51 UTC, sampoyigi requested changes

2021-05-31 08:51 UTC, sampoyigi commented on src/Cart/Helpers/CartConditionHelper.php
> +        $this->calculatedValue += round($value, $precision);
Let's pass the currency precision to the Cart library/CartCondition as config or property.

Should we also implement precision when calculating any money values within the Cart library.. For example, when calculating the cart item total?

2021-05-31 11:42 UTC, ryanmitchell commented
I dont think it does any harm to round it whenever we can. Certainly helps from a tax calculation point of view. If you can make a rough list of where and I’ll work through them.

In terms of passing the precision - is that not what app() helps you get around? You know laravel better than me :)


> On 31 May 2021, at 09:51, Sam Poyigi ***@***.***> wrote:
> 
> 
> @sampoyigi requested changes on this pull request.
> 
> In src/Cart/Helpers/CartConditionHelper.php <https://github.com/tastyigniter/flame/pull/34#discussion_r642326294>:
> 
> > +        $precision = app('currency')->getDefault() ? app('currency')->getDefault()->decimal_position : 2;
> +        $this->calculatedValue += round($value, $precision);
> Let's pass the currency precision to the Cart library/CartCondition as config or property.
> 
> Should we also implement precision when calculating any money values within the Cart library.. For example, when calculating the cart item total?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/tastyigniter/flame/pull/34#pullrequestreview-672099956>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAAMVOZCZLEU5IJBXCRPBCDTQNEYXANCNFSM45TQUK7Q>.
>

2021-06-04 13:19 UTC, sampoyigi commented
I'd say we tackle the rounding issue across the platform another time. 

Yup let's move this to the tax cart condition class and round the taxRate value.

No worries with passing the precision, we can use the currency service within the tax class.

2021-06-04 13:21 UTC, ryanmitchell commented
No worries - so back this out and just make it specific to the tax condition?

2021-06-05 05:50 UTC, sampoyigi commented
> No worries - so back this out and just make it specific to the tax condition?

Yup

2021-06-06 18:35 UTC, ryanmitchell commented
Opened a PR In cart

> On 5 Jun 2021, at 06:51, Sam Poyigi ***@***.***> wrote:
> 
> 
> No worries - so back this out and just make it specific to the tax condition?
> 
> Yup
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/tastyigniter/flame/pull/34#issuecomment-855188953>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAAMVOZKDAF7DYNTYCWFUILTRG3MZANCNFSM45TQUK7Q>.
>

2021-06-11 19:07 UTC, merged